//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocNghe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChungChiSinhVien
    {
        [Key]
        public int MaChungChiSinhVien { get; set; }
        public string IDSinhVien { get; set; }
        public int MaChungChi { get; set; }
        public System.DateTime NgayNhanChungChi { get; set; }
    
        public virtual ChungChi ChungChi { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
