//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocNghe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HopDong
    {
        [Key]
        public int MaHopDong { get; set; }
        public string IDSinhVien { get; set; }
        public string IDHuanLuyenVien { get; set; }
        public System.DateTime NgayTaoHopDong { get; set; }
        public System.DateTime NgayKetThucHopDong { get; set; }
    
        public virtual HuanLuyenVien HuanLuyenVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
