//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocNghe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.ChungChiSinhViens = new HashSet<ChungChiSinhVien>();
            this.HopDongs = new HashSet<HopDong>();
        }
        [Key]
        public string IDSinhVien { get; set; }
        public int MSSV { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string NgonNguLapTrinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string TrinhDoHocVan { get; set; }
        public Nullable<int> DiemTOEFL { get; set; }
        public string TinhTrangSinhVien { get; set; }
        public Nullable<int> DiemThiTracNghiem { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChungChiSinhVien> ChungChiSinhViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
